# Source: https://github.com/marketplace/actions/mkdocs-action#example-usage
name: MkDocs deploy page

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Update MAVLink tables
        run: python update_mavlink_tables.py --ignore-errors
      - name: Build HTML
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: "1.5.3"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
